---

- name: add VM guests to inventory
  hosts: localhost
  vars_files:
    - vars/vault.yml
    - vars/main.yml
  gather_facts: false
  tags: add-hosts
  tasks:
    - add_host:
        hostname: "{{ item.key }}"
        ansible_ssh_host: "{{ item.value.address }}"
        ansible_ssh_common_args: -o ProxyCommand="ssh -W %h:%p -q {{host_user}}@{{host_name}}" -o StrictHostKeyChecking=false -o UserKnownHostsFile=/dev/null
        ansible_user: cloud-user
        ansible_become: true
        groups: virtuals
      with_dict: "{{ virtual_machines }}"
      tags: vms_to_inventory

- name: set authorisation
  vars_files:
    - vars/vault.yml
    - vars/main.yml
  tags: add-auth
  hosts: "{{ master_name }}"
  roles:
    - ocp_post_auth

- name: Prepare infranode for hostpath
  hosts: "{{ infra_name }}"
  tags: add-registry
  vars_files:
    - vars/vault.yml
    - vars/main.yml
  roles:
    - ocp_post_local_hostpath_registry_filesystem

- name: Add hostpath volume to registry
  hosts: "{{ master_name }}"
  tags: add-registry
  vars_files:
    - vars/vault.yml
    - vars/main.yml
  roles:
    - ocp_post_local_hostpath_registry_oc

- name: Fix bugs
  tags: bug-fixes
  vars_files:
    - vars/vault.yml
    - vars/main.yml
  hosts: "{{ master_name }}, {{ infra_name }}, {{ apps1_name }}"
  tasks:
    - name: Fix bug with DNS
      lineinfile:
        dest: /etc/resolv.conf
        state: present
        insertafter: '# Generated by NetworkManager'
        line: 'search cluster.local'


- name: All done, ready to rock
  hosts: "{{host_name}}"
  tags: debug
  gather_facts: true
  vars_files:
    - vars/main.yml
  tasks:
    - name: All done, you can now login
      debug:
        msg:
          - "Login to Openshift:"
          - "oc login -u admin https://master.{{hostvars[ host_name ]['ansible_default_ipv4']['address']}}.nip.io:8443"
