---

- name: install packages for OCP install
  package: name={{ item }} state=present
  with_items:
    - atomic-openshift-utils
    - atomic-openshift-clients

- name: Create Inventory file
  template:
    src: hosts.j2
    dest: /etc/ansible/hosts

- name: Build hosts file
  lineinfile:
    dest=/etc/hosts
    regexp='.*{{ item.key }}$' line="{{ item.value.address }} {{ item.key }}"
    state=present
  with_dict: "{{ virtual_machines }}"
