---

- name: ensure all packages are up to date
  package: name=* state=latest

- name: install packages for OCP install
  vars:
    pkgs:
      - container-selinux
      - atomic-openshift-docker-excluder
      - wget
      - git
      - net-tools
      - bind-utils
      - iptables-services
      - bridge-utils
      - bash-completion
      - kexec-tools
      - sos
      - psacct
      - NetworkManager
      - cri-o
  package: name={{ pkgs }} state=present

- name: Build hosts file
  lineinfile:
    dest=/etc/hosts
    regexp='.*{{ item.key }}$' line="{{ item.value.address }} {{ item.key }}"
    state=present
  with_dict: "{{ virtual_machines }}"

- name: start NetworkManager
  service: name=NetworkManager state=started enabled=true

- name: Set cap on journald logs so they don't fill disks
  lineinfile:
    path: /etc/systemd/journald.conf
    regexp: 'SystemMaxUse='
    line: 'SystemMaxUse=1G'
  register: journal_result

- name: kick journald if needed
  service:
    name: systemd-journald
    state: restarted
  when: journal_result.changed

- name: add container storage mount point
  file:
    path: /var/lib/containers
    state: directory

- name: create filesystem for containers
  filesystem:
    fstype: xfs
    dev: "/dev/{{ container_disk }}"

- name: add container storage mount point
  mount:
    path: /var/lib/containers
    src: "/dev/{{ container_disk }}"
    fstype: xfs
    state: mounted

# We need some extra wiping, see
# htttps://bugzilla.redhat.com/show_bug.cgi?id=1572266

- name: Wipe possible ghost PV from gluster disk
  tags: wipe_pvs 
  command: "pvremove --force --force -y /dev/{{ ocs_disk }}"
  ignore_errors: yes
#  when: docker_storage_test.rc != 0

- name: Wipe the beginning of the disk from docker disk
  tags: wipe_pvs 
  command: "dd if=/dev/zero of={{ ocs_disk }} bs=1M count=4"
#  when: docker_storage_test.rc != 0
