---
# call this role with repos you want, eg:
# enabled_repos: [ rhel-7-server-rpms, rhel-7-server-optional-rpms,
#                  rhel-7-server-extras-rpms ]

- name: Subscribe to Red Hat
  tags: rhn
  redhat_subscription:
    state: present
    autosubscribe: false
    username: "{{ rh_sub_user }}"
    password: "{{ rh_sub_password }}"
    pool_ids: ["{{ rh_sub_pool }}"]
  register: subscribe

- name: Enable given repos
  tags: rhn
  rhsm_repository:
    name: "{{ enabled_repos }}"
    state: enabled
  with_items: "{{ enabled_repos }}"
