---
# call this role with repos you want, eg:
# enabled_repos: [ rhel-7-server-rpms, rhel-7-server-optional-rpms,
#                  rhel-7-server-extras-rpms ]

- name: Subscribe to Red Hat
  redhat_subscription:
    state: present
    autosubscribe: false
    username: "{{ rh_sub_user }}"
    password: "{{ rh_sub_password }}"
    pool: "{{ rh_sub_pool }}"
  register: subscribe

- name: Disable all the channels
  shell: |
    subscription-manager repos --disable='*'
  when: subscribe.changed

- name: Enable given repos
  shell: |
    subscription-manager repos --enable="{{ item }}"
  with_items: "{{ enabled_repos }}"
  when: subscribe.changed
