---

- name: Add scc for hostaccess
  command: "/usr/bin/oc adm policy add-scc-to-user hostaccess -z registry"
- name: Add volume to regisry dc
  command: "/usr/bin/oc volume dc/docker-registry --add -t hostPath --path /var/hostpath/registry -m /registry --name registry-storage --overwrite"
