---
# call this role with repos you want, eg:
# enabled_repos: [ rhel-7-server-rpms, rhel-7-server-optional-rpms,
#                  rhel-7-server-extras-rpms ]

- name: Subscribe to Red Hat
  redhat_subscription:
    state=present
    force_register=true
    autosubscribe=false
    username={{ rh_sub_user }}
    password={{ rh_sub_password }}
    pool={{ rh_sub_pool }}

- name: Disable all the channels
  shell: >
    subscription-manager repos --disable '*' &&
    touch /root/.rh-repos-once-disabled
    creates=/root/.rh-repos-once-disabled

- name: Enable repo rhel-server
  shell: >
    subscription-manager repos
    --enable="{{ item }}" &&
    touch /root/.rh-repos-{{ item }}
    creates=/root/.rh-repos-{{ item }}
  with_items: "{{ enabled_repos }}"
