---

- name: create http nat for infra
  tags: fw-host
  iptables:
    table: nat
    chain: PREROUTING
    in_interface: brinet
    protocol: tcp
    match: tcp
    destination_port: 80
    jump: DNAT
    to_destination: "{{ virtual_machines['ocp-infra'].address }}"
    #to_ports: 80  XXX ansible bug?
    comment: Redirect http traffic to infranode

- name: create http nat MASQUERADE for infra
  tags: fw-host
  iptables:
    table: nat
    chain: POSTROUTING
    protocol: tcp
    destination_port: 80
    jump: MASQUERADE
    destination: "{{ virtual_machines['ocp-infra'].address }}"
    comment: Masquerade http traffic from infranode

- name: create https nat for infra
  tags: fw-host
  iptables:
    table: nat
    chain: PREROUTING
    in_interface: brinet
    protocol: tcp
    match: tcp
    destination_port: 443
    jump: DNAT
    to_destination: "{{ virtual_machines['ocp-infra'].address }}"
    #to_ports: 443 XXX ansible bug?
    comment: Redirect https traffic to infranode

- name: create https nat MASQUERADE for infra
  tags: fw-host
  iptables:
    table: nat
    chain: POSTROUTING
    protocol: tcp
    destination_port: 443
    jump: MASQUERADE
    destination: "{{ virtual_machines['ocp-infra'].address }}"
    comment: Masquerade https traffic from infranode

- name: create https nat for master API
  tags: fw-host
  iptables:
    table: nat
    chain: PREROUTING
    in_interface: brinet
    protocol: tcp
    match: tcp
    destination_port: 8443
    jump: DNAT
    to_destination: "{{ virtual_machines['ocp-master'].address }}"
    #to_ports: 8443 XXX ansible bug?
    comment: Redirect 8443 https traffic to master API

- name: create https nat MASQUERADE for master
  tags: fw-host
  iptables:
    table: nat
    chain: POSTROUTING
    protocol: tcp
    destination_port: 8443
    jump: MASQUERADE
    destination: "{{ virtual_machines['ocp-master'].address }}"
    comment: Masquerade https traffic from master

# - name: mark ssh connections
#   XXX Ansible does not have recent iptables module
#   command: iptables -I INPUT -p tcp --dport 22 -i eth0 -m state --state NEW -m recent --set
#   iptables:
#     chain: INPUT
#     protocol: tcp
#     destination_port: 22
#     in_interface: brinet
#     ctstate: NEW


- name: slow down brute force ssh attacks
  tags: fw-host
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: 22
    ctstate: NEW
    in_interface: brinet
    limit: 2/minute
    jump: DROP
