---

- name: define and start guests
  vars_files:
    - vars/vault.yml
    - vars/main.yml
  tags: create-guests
  hosts: "{{ host_name }}"
  roles:
    - virt-guests
    - firewall-host

- name: add VM guests to inventory and wait for being up
  hosts: localhost
  vars_files:
    - vars/vault.yml
    - vars/main.yml
  tasks:
    - name: add guests to inventory
      add_host:
        hostname: "{{ item.key }}"
        ansible_ssh_host: "{{ item.value.address }}"
        ansible_ssh_common_args: -o ProxyCommand="ssh -W %h:%p -q {{host_user}}@{{host_name}}" -o StrictHostKeyChecking=false -o UserKnownHostsFile=/dev/null
        ansible_user: cloud-user
        ansible_become: true
        groups: virtuals
      with_dict: "{{ virtual_machines }}"
      tags: vms_to_inventory
    - name: wait 300 seconds, but only start checking after 30 seconds
      wait_for_connection:
        delay: 30
        timeout: 300

- name: create access config for guests
  vars_files:
    - vars/vault.yml
    - vars/main.yml
  tags: access_config
  hosts: localhost
  connection: local
  roles:
    - ssh_proxy
    - ocp_local_ansible_hosts_file

- name: subscribe guests
  vars_files:
    - vars/vault.yml
    - vars/main.yml
  tags: rh-subs
  hosts: virtuals
  serial: 1 # needed, as subscription-manager is such a piece of shit.
  tasks:
    - include_role:
        name: rhn
      vars:
        enabled_repos:
          - rhel-7-server-rpms
          - rhel-7-server-optional-rpms
          - rhel-7-server-extras-rpms
          - rhel-7-server-ose-3.6-rpms
          - rhel-7-fast-datapath-rpms
        when: do_subscribe

- name: prepare OCP bastion
  hosts: "{{ bastion_name }}"
  vars_files:
    - vars/vault.yml
    - vars/main.yml
  tags: prep_bastion
  vars:
   - ansible_user: cloud-user
   - ansible_become: true
  roles:
    - ocp_bastion

- name: prepare nodes
  hosts: "{{ master_name }}, {{ infra_name }}, {{ apps1_name }}"
  vars_files:
    - vars/vault.yml
    - vars/main.yml
  tags: prep_nodes
  roles:
    - ocp_node

- name: Infra is done, ready to install OCP
  hosts: localhost
  vars_files:
    - vars/vault.yml
    - vars/main.yml
  gather_facts: false
  tasks:
  - name: Now install OCP, you must login to {{bastion_name}} to run OCP ansible installer
    debug:
      msg:
      - "SSH to {{bastion_name}} to run ansible installer:"
      - "ssh -F /tmp/ocp-bastion-ssh.config -A {{virtual_machines[ 'bastion' ].address}}""
      - "ansible-playbook /usr/share/ansible/openshift-ansible/playbooks/byo/config.yml"
