---

- name: define and start guests
  vars_files:
    - vars/vault.yml
    - vars/main.yml
  hosts: "{{ host_name }}"
  roles:
    - virt-guests
    - firewall-host

- name: create access config for guests
  vars_files:
    - vars/vault.yml
    - vars/main.yml
  tags: access_config
  hosts: localhost
  connection: local
  roles:
    - ssh_proxy
    - ocp_local_ansible_hosts_file

- name: subscribe guests
  vars_files:
    - vars/vault.yml
    - vars/main.yml
  tags: rh-subs
  vars:
   - ansible_user: cloud-user
   - ansible_become: true
  hosts: virtuals
  tasks:
    - include_role:
        name: rhn
      vars:
        enabled_repos:
          - rhel-7-server-rpms
          - rhel-7-server-optional-rpms
          - rhel-7-server-extras-rpms
          - rhel-7-server-ose-3.6-rpms
          - rhel-7-fast-datapath-rpms
